### ISSUE TITLE
timelapse doesn't work

### ISSUE THREAD

**Issue by borislavstefanov** [mainsail-crew/moonraker-timelapse#106]
where am I going wrong with the installation, after printing it only saves a rar file which is 1 kbyte with 1 picture you can't even load.  The printer is Voron 2.4 with raspbery 3+, raspbery cam ,

**Comment by FrYakaTKoP** [comment]
can you provide a moonraker.log with a failed print/timelapse? My guess is that you didn't specify a correct snapshot url. If you define a snapshoturl with a stream rather than a still image, timelapse will try to get the stream and aborts collection after 2 sec (timeout), but since the stream doesn't end (mpjeg streams are continuous) the collected frame will be 0 bytes and therefore the render fails and the "save frames" zip file will only contain a empty jpeg file.

**Comment by borislavstefanov** [comment]
https://github.com/borislavstefanov/Voron-2.4-delluks-files-/blob/main/moonraker%20(1).log

**Comment by FrYakaTKoP** [comment]
🤔 my guess is that wget (timelapse uses internally to collect the snaphot) can't resolve `http://192.168.88.37:8080/?action=snapshot` because of the explicit ip address in there. 

the default config for `URL snapshot` in the webcams settings would be: 
```/webcam/?action=snapshot``` 
without any ip. Could you try that first, it should resolve the issue with timelapse with that.

If you need to have explicit ip in there for mainsail to work we will figure out something that will work for both timelapse and mainsail, but first we need to know if we are on the right track.

**Comment by borislavstefanov** [comment]
Is that how it should be?

[timelapse]
enabled: True
mode: layermacro
snapshoturl: /webcam/?action=snapshot
gcode_verbose: True
parkhead: False
parkpos: back_left
park_custom_pos_x: 0.0
park_custom_pos_y: 0.0
park_custom_pos_dz: 0.0
park_travel_speed: 100
park_retract_speed: 15
park_extrude_speed: 15
park_retract_distance: 1.0
park_extrude_distance: 1.0
hyperlapse_cycle: 30
autorender: True
constant_rate_factor: 23
output_framerate: 30
pixelformat: yuv420p
time_format_code: %Y%m%d_%H%M
extraoutputparams: 
variable_fps: False
targetlength: 10
variable_fps_min: 5
variable_fps_max: 60
flip_x: False
flip_y: False
duplicatelastframe: 0
previewimage: True
saveframes: True

**Comment by FrYakaTKoP** [comment]
yes and no. You shouldn't use moonraker.conf anymore to setup timelapse. This settings should be all in your webinterface of joice (like mainsail), but yes the the snapshoturl looks correct

**Comment by FrYakaTKoP** [comment]
in mainsail (i think in fluidd too but not sure) there are cog wheels in the right top corner:

![image](https://user-images.githubusercontent.com/10913183/231174746-65c09649-a8e1-404d-aa13-3babfa3d4b0e.png)

then navigate to "webcams" and setup your camera there:

![image](https://user-images.githubusercontent.com/10913183/231175329-f8a37e8a-9c0d-4456-b7c0-86dfcf930aeb.png)

![image](https://user-images.githubusercontent.com/10913183/231175493-aa7c46b9-1358-48a1-abd3-3c72c3df2de3.png)

then navigate to "timelapse" and add your settings there:

![image](https://user-images.githubusercontent.com/10913183/231175882-cd0f3c5f-8282-4bd7-a569-f5180bcb65e3.png)
(make sure you select the camera you just setup or it won't work)

after that delete everything (maybe download a backup first) in the timelapse section of moonraker.conf, but leave `[timelapse]` it should look like this afterwards:

```
[timelapse]
```

now you should be able to edit settings directly in mainsail, also you can select if you like to activate timelapse when starting a print (if you may decide this print doesn't need a TL)

**Comment by FrYakaTKoP** [comment]
so you can't select a camera in timelapse settings?

**Comment by borislavstefanov** [comment]
yes is not active 
![image](https://user-images.githubusercontent.com/6666322/231183230-fc953b03-d024-46a8-81d4-feb485492b1a.png)

![image](https://user-images.githubusercontent.com/6666322/231182870-723bc5f6-8a3a-4faf-8690-b86ee3656b7a.png)

**Comment by FrYakaTKoP** [comment]
can you show a screenshot of the webcams settings?

**Comment by FrYakaTKoP** [comment]
strange after clicking "update webcam" you should be able to select the camera in timelapse settings

**Comment by borislavstefanov** [comment]
I added the camera again and it started, maybe it needed some time to refresh

**Comment by FrYakaTKoP** [comment]
so can you now confirm that frame collection works? Do following:
execute the "TIMELAPSE_TAKE_FRAME" macro in the dashboard or via gcode console
you now should see that frame in the status panel of the timelapse tab

**Comment by borislavstefanov** [comment]
confirm works, thank you very much for your help

**Comment by FrYakaTKoP** [comment]
you're welcome. Now do a print and confirm you receive a timelapse afterwards, if so close this issue.

**Comment by borislavstefanov** [comment]
it works, everything is as it should be now. thank you very much again
